name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Test
        run: make test && cd bin && ./test && cd ../ && make clean-test

      - name: Check codestyle
        run: git ls-files *.{cpp,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make
